services:
  mosquitto:
    image: eclipse-mosquitto:openssl
    
    container_name: mosquitto
    build:
      context: ./Mosquitto_MQTT_Broker
      dockerfile: Dockerfile
    volumes:
      - ./Mosquitto_MQTT_Broker/config:/mosquitto/config
      #- ./certificates/:/mosquitto/certs
    ports:
      # MQTT port
      - "1883:1883"
      # WebSocket port for MQTT over WebSockets
      - "9001:9001" 
    stdin_open: true 
    tty: true

  nginx:
    build: 
      context: ./SpecialNginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "1935:1935"
    volumes:
      - ./SpecialNginx/nginx.conf:/etc/nginx/nginx.conf
      - ./SpecialNginx/test.html:/var/www/html/src/test.html
      - ./SpecialNginx/turnserver.conf:/etc/turnserver.conf
    environment:
      CONTAINER_IP: "172.17.0.2/16"
    command: >
      nginx -g 'daemon off;' && 
      echo 'Starting TURN server...' && 
      cd /var/www/html/src/ && mkdir hls &&
      cd /var/www/html/src/ && mkdir rec &&
      sed -i 's/#TURNSERVER_ENABLED=1/TURNSERVER_ENABLED=1/g' /etc/default/coturn && 
      /usr/bin/turnserver -o -v -n --no-stun --no-udp -r domain.com -a -f -u user:password -L 0.0.0.0 --cert /etc/ssl/private/turn_server_cert.pem --pkey /etc/ssl/private/turn_server_pkey.pem --log-file stdout && 
      echo 'Generating Nginx certificates...' && 
      openssl genpkey -algorithm RSA -out /etc/ssl/private/nginxHTTPS_pkey.pem && 
      openssl req -new -key /etc/ssl/private/nginxHTTPS_pkey.pem -out /etc/ssl/private/nginxHTTPS_csr.pem -subj '/C=/ST=/L=/O=Corp/OU=/CN=' && 
      openssl x509 -req -days 365 -in /etc/ssl/private/nginxHTTPS_csr.pem -signkey /etc/ssl/private/nginxHTTPS_pkey.pem -out /etc/ssl/private/nginxHTTPS_cert.pem"
